name: Secrets Scan

on:
  push:
    branches-ignore: []
  pull_request:
    branches: [main]

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: TruffleHog OSS filesystem scan
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ""
          head: HEAD
          extra_args: --only-verified --exclude-paths=.trufflehogignore
        continue-on-error: false
